/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#c2c6d6',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        outline: '#8c909f',
        'outline-variant': '#424754',
        'surface-tint': '#adc6ff',
        primary: '#adc6ff',
        'on-primary': '#002e6a',
        'primary-container': '#4d8eff',
        'on-primary-container': '#00285d',
        'inverse-primary': '#005ac2',
        secondary: '#ddb7ff',
        'on-secondary': '#490080',
        'secondary-container': '#6f00be',
        'on-secondary-container': '#d6a9ff',
        tertiary: '#ffb95f',
        'on-tertiary': '#472a00',
        'tertiary-container': '#ca8100',
        'on-tertiary-container': '#3e2400',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        success: '#22c55e',
        warning: '#ffb95f',
        background: '#0b1326',
        'on-background': '#dae2fd',
        'surface-variant': '#2d3449',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        'sidebar-width': '260px',
        unit: '4px',
        'container-padding': '24px',
        'stack-gap': '12px',
      },
      boxShadow: {
        'glow-primary': '0 0 24px -6px rgba(173,198,255,0.55)',
        'glow-secondary': '0 0 24px -6px rgba(221,183,255,0.55)',
        'glow-tertiary': '0 0 24px -6px rgba(255,185,95,0.55)',
        'glow-success': '0 0 24px -6px rgba(34,197,94,0.55)',
        'glow-error': '0 0 24px -6px rgba(255,180,171,0.55)',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: 0, transform: 'translateY(4px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        pulse: {
          '0%,100%': { opacity: 1 },
          '50%': { opacity: 0.6 },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.18s ease-out',
      },
    },
  },
  plugins: [],
};
